import { Application } from 'express';
import swaggerUi from 'swagger-ui-express';
import { RegisterRoutes } from '../routes/routes';

export function swaggerDocs(app: Application) {
  // Serve Swagger UI
  app.use(
    '/api-docs',
    swaggerUi.serve,
    swaggerUi.setup(undefined, {
      swaggerOptions: {
        url: '/swagger.json',
        explorer: true
      }
    })
  );

  // Serve OpenAPI/Swagger JSON
  app.get('/swagger.json', (req, res) => {
    res.sendFile('swagger.json', { root: '.' });
  });

  // Register routes generated by tsoa
  RegisterRoutes(app);
} 