version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - context-keeper-data:/app/.context-keeper
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: context-keeper/dashboard/public/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./context-keeper/dashboard/public:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  context-keeper-data:
    driver: local 